# docker-compose.yml (version 1.02)
# This file is for LOCAL DEVELOPMENT and TESTING ONLY.
# It allows us to reliably run the application in a container,
# mimicking the production environment.

services:
  app:
    # Build the image from the Dockerfile in the current directory.
    build: .
    # Use the .env file to supply environment variables to the container.
    # docker-compose has a robust parser that handles special characters correctly.
    env_file:
      - .env
    # Map port 3000 on your local machine to port 3000 inside the container.
    ports:
      - "3000:3000"
    # Give the container a friendly name.
    container_name: headlines_local