app = 'headlines-polished-sea-1731'
primary_region = 'lhr'

# This empty [processes] block tells flyctl to use the modern Machines platform
# and not look for a long-running web service.
[processes]

# We define a template for a machine that can be started on demand.
[[machines]]
  # This machine will not run on a simple schedule from Fly.
  # schedule = 'hourly' <-- REMOVE THIS LINE
  
  # The machine will be destroyed after its task is complete.
  auto_destroy = true
  # When created during deploy, it will be in a 'stopped' state, costing nothing for CPU/RAM.
  initial_state = "stopped"
  
  [machines.vm]
    memory = '4gb'
    cpu_kind = 'shared'
    cpus = 1