app = 'headlines-polished-sea-1731'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # <-- CHANGE THIS
  auto_start_machines = true
  min_machines_running = 1    # <-- CHANGE THIS
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1