app = 'headlines-polished-sea-1731'
primary_region = 'lhr'

# We are no longer an HTTP service.
# [http_service] section is removed.

# We define a scheduled machine instead.
[[machines]]
  schedule = "0 */2 * * *" # This is the same cron schedule: every 2 hours
  
  [machines.vm]
    memory = '4gb'
    cpu_kind = 'shared'
    cpus = 2