# fly.toml (The Final, Correct Version)
app = 'headlines-polished-sea-1731'
primary_region = 'lhr'

# This empty [processes] block is the key.
# It tells flyctl to use the modern Machines platform deployment logic
# and to not look for a long-running web service.
[processes]

# --- TEST SCHEDULE ---
# This schedule will now be correctly applied by the Machines platform.
[[machines]]
  schedule = 'hourly'
  
  [machines.vm]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1