name: Run Pipeline on Schedule

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    # IMPORTANT: GitHub schedules run on UTC time.
    # 10:00 Copenhagen (CEST, UTC+2) is 08:00 UTC
    # 16:30 Copenhagen (CEST, UTC+2) is 14:30 UTC
    - cron: '0 6 * * *'
    - cron: '0 8 * * *'
    - cron: '30 14 * * *'
    - cron: '39 22 * * *'

jobs:
  run-on-fly:
    name: Start a Fly Machine to Run the Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - uses: actions/checkout@v4
      
      # Step 2: Set up the flyctl command-line tool
      # MODIFIED: Corrected to the latest stable version @v1.8
      - uses: superfly/flyctl-actions/setup-flyctl@v1.8
        
      # Step 3: Run the command with explicit and consistent configuration
      - name: Start a temporary machine and wait for completion
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # Aligned memory with the valid fly.toml configuration.
          fly machine run . --region lhr --memory 2048
          
          echo "The machine has completed its run and has been destroyed."