# File: .github/workflows/schedule_run.yml (version 1.01)
name: Scheduled Pipeline Run

on:
  schedule:
    - cron: "0 */2 * * *" # Every 2 hours
  workflow_dispatch: # Allow manual triggering

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Fly.io App Pipeline
        run: |
          echo "Triggering pipeline at ${{ secrets.FLY_APP_URL }}/run-pipeline"
          
          response=$(curl -s -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.PIPELINE_TRIGGER_KEY }}" \
            "${{ secrets.FLY_APP_URL }}/run-pipeline")
          
          http_code=$(tail -n1 <<< "$response")
          body=$(head -n -1 <<< "$response")

          echo "HTTP Status Code: $http_code"
          echo "Response Body: $body"

          if [ "$http_code" -ne 202 ]; then
            echo "::error::Pipeline trigger failed with status code $http_code"
            exit 1
          fi
          
          echo "Pipeline successfully triggered."